version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - chmod +x bin/build.sh
  build:
    commands:
      - echo "Building Metabase application..."
      - ./bin/build.sh

